### ISSUE TITLE
problem with commonmodule and emitter

### ISSUE THREAD

**Issue by vrecon** [franzeal/ngx-formly-designer#25]
When building the application an error occurs int he emitter.js.
⠋ Generating browser application bundles (phase: setup).../Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:171
                throw new Error("Symbol " + ref.debugName + " declared in " + typescript_1.getSourceFile(ref.node).fileName + " is not exported from " + specifier + " (import into " + context.fileName + ")");
                      ^

Error: Symbol CommonModule declared in /Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/common/common.d.ts is not exported from @angular/common (import into /Users/bvredevoort/Downloads/ngx-formly-designer-main/src/app/app.module.ts)
    at AbsoluteModuleStrategy.emit (/Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:171:23)
    at ReferenceEmitter.emit (/Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at Object.toR3Reference (/Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:247:18)
    at NgModuleDecoratorHandler._toR3Reference (/Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:527:31)
    at /Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:266:72
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (/Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:266:38)
    at TraitCompiler.analyzeTrait (/Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:421:40)
    at analyze (/Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:371:58)
    at _loop_1 (/Users/bvredevoort/Downloads/ngx-formly-designer-main/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:393:21)

How can we fix this?

**Comment by franzeal** [comment]
Tried a fresh clone and not encountering the issue.  Is there more context that would help me reproduce this issue?  Otherwise, not sure how I can help.

**Comment by vrecon** [comment]
My bad, wrong node version on a new mac m1 .
